### ISSUE TITLE
Cell status indicator gets stuck on "running"

### ISSUE THREAD

**Issue by psychemedia** [r-wasm/jupyterlite-webr-kernel#2]
On running a code cell, the cell run indicator shows a running (`*`) status, as expected, but when the cell completes execution, the cell indicator still displays the running symbol, rather than the code history line execution number:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/82988/224288569-d62e63da-3f67-4fef-9033-3684283438e2.png">

**Comment by georgestagg** [comment]
This should now be fixed as of 3c22ad52714acc6262ad7d7568a85128712a7da1.
